
services:
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/backend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./services/auth-service/backend/.env
    working_dir: /app/services/auth-service/backend
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  pdf-service:
    build:
      context: .
      dockerfile: services/pdf-service/backend/Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./services/pdf-service/backend/.env
    working_dir: /app/services/pdf-service/backend
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath=/dev/null"]

volumes:
  mongo-data:
