import { User, Signature, CorporateSeal, Notification, UserRole } from '../types';

export const mockUserProfiles: Record<UserRole, User> = {
  regularUser: {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "+1 (555) 123-4567",
    company: "Acme Corp",
    position: "Software Engineer",
    department: "Engineering",
    employeeId: "EMP001",
    bio: "Passionate software engineer with 5 years of experience in web development.",
    website: "https://johndoe.dev",
    linkedIn: "https://linkedin.com/in/johndoe",
    role: "regularUser",
    organization: "Acme Corp",
    profilePhoto: undefined,
    createdAt: "2024-01-15T10:30:00Z",
    lastLogin: "2024-07-01T09:15:00Z",
    isEmailVerified: true,
    isMFAEnabled: false,
    addresses: [
      {
        id: 1,
        type: 'home',
        street: '123 Main St',
        city: 'New York',
        state: 'NY',
        zipCode: '10001',
        country: 'USA',
        isPrimary: true,
      },
    ],
    emails: [
      {
        id: 1,
        email: 'john@example.com',
        type: 'primary',
        isVerified: true,
        isPrimary: true,
      },
    ],
    phones: [
      {
        id: 1,
        number: '+1 (555) 123-4567',
        type: 'mobile',
        isVerified: true,
        isPrimary: true,
      },
    ],
  },
  teamAdmin: {
    id: 2,
    name: "Jane Smith",
    email: "jane@acme.com",
    phone: "+1 (555) 987-6543",
    company: "Acme Corp",
    position: "VP of Operations",
    department: "Operations",
    employeeId: "EMP002",
    bio: "Experienced operations leader focused on streamlining business processes and team efficiency.",
    website: "https://acme.com",
    linkedIn: "https://linkedin.com/in/janesmith",
    twitter: "https://twitter.com/janesmith",
    role: "teamAdmin",
    organization: "Acme Corp",
    profilePhoto: undefined,
    createdAt: "2024-01-10T08:00:00Z",
    lastLogin: "2024-07-01T08:30:00Z",
    isEmailVerified: true,
    isMFAEnabled: true,
    addresses: [
      {
        id: 1,
        type: 'work',
        street: '456 Business Ave',
        city: 'New York',
        state: 'NY',
        zipCode: '10002',
        country: 'USA',
        isPrimary: true,
      },
    ],
    emails: [
      {
        id: 1,
        email: 'jane@acme.com',
        type: 'work',
        isVerified: true,
        isPrimary: true,
      },
      {
        id: 2,
        email: 'jane.smith@personal.com',
        type: 'personal',
        isVerified: true,
        isPrimary: false,
      },
    ],
    phones: [
      {
        id: 1,
        number: '+1 (555) 987-6543',
        type: 'work',
        isVerified: true,
        isPrimary: true,
      },
    ],
  },
  superAdmin: {
    id: 3,
    name: "Alex Johnson",
    email: "alex@draftsign.com",
    phone: "+1 (555) 111-2222",
    company: "DraftSign Inc",
    position: "Chief Technology Officer",
    department: "Technology",
    employeeId: "ADMIN001",
    bio: "Technology leader with expertise in document management systems and enterprise software architecture.",
    website: "https://draftsign.com",
    linkedIn: "https://linkedin.com/in/alexjohnson",
    twitter: "https://twitter.com/alexjohnson",
    role: "superAdmin",
    organization: "DraftSign Inc",
    profilePhoto: undefined,
    createdAt: "2024-01-01T00:00:00Z",
    lastLogin: "2024-07-01T07:00:00Z",
    isEmailVerified: true,
    isMFAEnabled: true,
    addresses: [
      {
        id: 1,
        type: 'work',
        street: '789 Tech Plaza',
        city: 'San Francisco',
        state: 'CA',
        zipCode: '94105',
        country: 'USA',
        isPrimary: true,
      },
    ],
    emails: [
      {
        id: 1,
        email: 'alex@draftsign.com',
        type: 'work',
        isVerified: true,
        isPrimary: true,
      },
    ],
    phones: [
      {
        id: 1,
        number: '+1 (555) 111-2222',
        type: 'work',
        isVerified: true,
        isPrimary: true,
      },
    ],
  },
};

export const mockSignatures: Record<UserRole, Signature[]> = {
  regularUser: [
    {
      id: 1,
      name: "Primary Signature",
      type: "drawn",
      data: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjgwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGQ9Ik0xMCAzMCBRIDUwIDEwIDEwMCAzMCBRIDE1MCA1MCAyMDAgMzAiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLXdpZHRoPSIyIiBmaWxsPSJub25lIi8+PC9zdmc+",
      color: "#000000",
      isDefault: true,
      createdAt: "2024-06-15T10:00:00Z",
      lastUsed: "2024-07-01T09:15:00Z",
    },
    {
      id: 2,
      name: "Initials",
      type: "typed",
      data: "JD",
      font: "Arial",
      color: "#000000",
      size: 24,
      style: "normal",
      isDefault: false,
      createdAt: "2024-06-20T14:30:00Z",
    },
  ],
  teamAdmin: [
    {
      id: 1,
      name: "Official Signature",
      type: "drawn",
      data: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjUwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgNTAgUSA2MCAyMCAxMjAgNTAgUSAxODAgODAgMjUwIDUwIiBzdHJva2U9IiMwMDAiIHN0cm9rZS13aWR0aD0iMyIgZmlsbD0ibm9uZSIvPjwvc3ZnPg==",
      color: "#000000",
      isDefault: true,
      createdAt: "2024-05-01T09:00:00Z",
      lastUsed: "2024-07-01T08:30:00Z",
    },
    {
      id: 2,
      name: "Quick Initial",
      type: "typed",
      data: "JS",
      font: "Times New Roman",
      color: "#1e40af",
      size: 28,
      style: "italic",
      isDefault: false,
      createdAt: "2024-05-05T11:00:00Z",
    },
    {
      id: 3,
      name: "VP Signature",
      type: "uploaded",
      data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      isDefault: false,
      createdAt: "2024-05-10T16:00:00Z",
    },
  ],
  superAdmin: [
    {
      id: 1,
      name: "Executive Signature",
      type: "drawn",
      data: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAwIiBoZWlnaHQ9IjEyMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgNjAgUSA4MCAyMCAxNjAgNjAgUSAyNDAgMTAwIDMwMCA2MCIgc3Ryb2tlPSIjMDAwIiBzdHJva2Utd2lkdGg9IjQiIGZpbGw9Im5vbmUiLz48L3N2Zz4=",
      color: "#000000",
      isDefault: true,
      createdAt: "2024-01-01T12:00:00Z",
      lastUsed: "2024-07-01T07:00:00Z",
    },
    {
      id: 2,
      name: "CTO Initials",
      type: "typed",
      data: "AJ",
      font: "Helvetica",
      color: "#dc2626",
      size: 32,
      style: "bold",
      isDefault: false,
      createdAt: "2024-01-05T10:00:00Z",
    },
  ],
};

export const mockCorporateSeals: Record<UserRole, CorporateSeal[]> = {
  regularUser: [],
  teamAdmin: [
    {
      id: 1,
      name: "Company Official Seal",
      type: "official",
      data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      description: "Official company seal for legal documents",
      permissions: ["teamAdmin", "superAdmin"],
      createdAt: "2024-02-01T10:00:00Z",
      lastUsed: "2024-06-30T15:00:00Z",
    },
    {
      id: 2,
      name: "Operations Department Seal",
      type: "department",
      data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      description: "Operations department approval seal",
      permissions: ["teamAdmin"],
      createdAt: "2024-02-15T14:00:00Z",
    },
  ],
  superAdmin: [
    {
      id: 1,
      name: "Corporate Executive Seal",
      type: "official",
      data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      description: "Executive level corporate seal",
      permissions: ["superAdmin"],
      createdAt: "2024-01-01T12:00:00Z",
      lastUsed: "2024-07-01T07:00:00Z",
    },
    {
      id: 2,
      name: "Technology Division Seal",
      type: "department",
      data: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      description: "Technology division official seal",
      permissions: ["superAdmin"],
      createdAt: "2024-01-10T09:00:00Z",
    },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 1,
    type: "signature_request",
    title: "New signature request",
    message: "Document 'Q3_Contract_2024.pdf' requires your signature",
    timestamp: "2024-07-01T08:30:00Z",
    read: false,
    priority: "high",
    actionUrl: "/documents/123",
  },
  {
    id: 2,
    type: "document_completed",
    title: "Document completed",
    message: "All parties have signed 'Partnership_Agreement.pdf'",
    timestamp: "2024-06-30T16:45:00Z",
    read: false,
    priority: "medium",
  },
  {
    id: 3,
    type: "system_update",
    title: "System maintenance scheduled",
    message: "Scheduled maintenance on July 5th from 2-4 AM EST",
    timestamp: "2024-06-29T10:00:00Z",
    read: true,
    priority: "low",
  },
  {
    id: 4,
    type: "security_alert",
    title: "New device login",
    message: "New login detected from iPhone in New York, NY",
    timestamp: "2024-06-28T18:30:00Z",
    read: true,
    priority: "medium",
  },
  {
    id: 5,
    type: "team_activity",
    title: "Team member added",
    message: "Sarah Wilson has been added to your organization",
    timestamp: "2024-06-27T14:15:00Z",
    read: true,
    priority: "low",
  },
];